[book]
authors = ["januborer"]
language = "en"
multilingual = false
src = "src"
title = "老子"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = true
copy-fonts = true
no-section-label = false
git-repository-url = "https://github.com/januborer/laozi"
git-repository-icon = "fa-github"
site-url = "/laozi/"

[output.html.print]
enable = false
page-break = true

[output.html.fold]
enable = true
level = 0


[output.html.search]
enable = false # enables the search feature
limit-results = 30       # maximum number of search results
teaser-word-count = 30   # number of words used for a search result teaser
use-boolean-and = true   # multiple search terms must all match
boost-title = 2          # ranking boost factor for matches in headers
boost-hierarchy = 1      # ranking boost factor for matches in page names
boost-paragraph = 1      # ranking boost factor for matches in text
expand = true            # partial words will match longer terms
heading-split-level = 3  # link results to heading levels
copy-js = true           # include Javascript code for search


[output.html.playground]
editable = true
runnable = false
