#!/bin/sh

###############Deploy##############

# If a command fails then the deploy stops set -e 
printf "\033[0;32mDeploying updates to GitHub...\033[0m\n"

# Build the project.
# hugo # if using a theme, replace with `hugo -t <YOURTHEME>`

# Go To Public folder
#
mdbook build
cd book

git init
git branch -m laozi-site
git remote add origin git@github.com:januborer/laozi.git

current_branch=$(git branch --show-current)
# Add changes to git.
git add -f .

# Commit changes.
msg="rebuilding site $(date)"
if [ -n "$*" ]; then
    msg="$*"
fi
git commit -m "$msg"

# Push source and build repos.
git push -f origin $current_branch
